### ISSUE TITLE
Move release packages to Github

### ISSUE THREAD

**Issue by henridf** [brimdata/build-suricata#28]
Releases are currently stored in a public Google Cloud bucket. We should move them to be on the GitHub Releases page for this repo (like we do for zeek).

**Comment by henridf** [comment]
This should be a good time to move to tag-based releases and versioning (@alfred-landrum 
 started a branch for this here: https://github.com/brimsec/build-suricata/tree/tag-versioning )

**Comment by philrz** [comment]
I've verified that these can be generated via typical GitHub workflow, as evidenced by the artifacts at https://github.com/brimsec/build-suricata/releases/tag/v5.0.3-brim26. I confirmed at least one of them was usable when I verified #28 just now. I did, however, notice a minor issue with the paths that is being tracked in #53.

Thanks @henridf!
