### ISSUE TITLE
Tidy up suricata package

### ISSUE THREAD

**Issue by henridf** [brimdata/build-suricata#35]
The suricata packages bundle stuff that isn't needed. Clean this up.

**Comment by philrz** [comment]
Verified with the `suricata-v5.0.3-brim25` artifact on macOS.

Short of enumerating every file that's been trimmed, here's a macro-level view. As of the `suricata-v5.0.3-brim21` artifact that pre-dated this enhancement:

```
suricata-v5.0.3-brim21$ find . | wc -l
     223
```

Then with the `suricata-v5.0.3-brim25` artifact:

```
suricata-v5.0.3-brim25$ find . | wc -l
      62
```

Obviously it's important that none of the trimmed files caused us to lose functionality, but we'll be keeping an eye on that as we continue testing as we finalize the introduction of Suricata to Brim.

Thanks @henridf!
